### PR TITLE
Ports from hyper that probably work (feat. Dullahans)

### PR DESCRIPTION
**Pull request by christiankabbalahexpert**
## About The Pull Request

Mostly ports; some lighting effects that probably won't be very visible since I don't think anything uses them (yet), smooth pixel shifting, and some emotes. Plus I enabled dullahans.

If you wanna make sure everything is tested, here's a checklist:
make and play a dullahan character
do some pixel shifting
use these emotes: cough, sniff, tesh_sneeze, racc_chitter, and bat_chitter.

## Why It's Good For The Game

Quality of life, plus these are easy to add so why not tbh.

## Changelog
:cl:
add: Added new things
tweak: tweaked a few things
soundadd: added a new sound thingy
/:cl:

### CODE REVIEW

**Comment by halolegend2000** [comment]
wow i love the vague-ass changelog that i read when i get this in my emails. so so good of you dude

**Comment by christiankabbalahexpert** [comment]
> wow i love the vague-ass changelog that i read when i get this in my emails. so so good of you dude

 wow cool no wonder GS has so many coders ready and willing to work on it when the response they get is as positive as yours you absolute imbecile

**Comment by MrSky12** [comment]
Always positive things from Halolegend.

**Comment by evilew** [comment]
> wow i love the vague-ass changelog that i read when i get this in my emails. so so good of you dude

Unsubscribe from getting emails about this, you dimwit

**Pull request merged**
